/**
 * LiveStockProfile - Maintains dynamic live 10-metric profiles for all tracked stocks
 */

export const TRACKED_STOCKS_PROFILES = {
  TCS: {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    cmp: 4150.0,
    trend: 'Strong Bullish',
    momentumScore: 92,
    institutionalScore: 94,
    newsScore: 88,
    technicalScore: 90,
    fundamentalScore: 95,
    volumeScore: 91,
    riskScore: 85, // 85 = Low Risk
    confidenceScore: 92,
    overallOpportunityScore: 93,
    signal: 'HIGH CONVICTION BUY',
    entryZone: '₹3785 - ₹3810',
    stopLoss: '₹3690',
    targetZone: '₹4020 - ₹4150',
    holdingPeriod: '12 Days',
    invalidation: 'Close below ₹3690 or FII net outflow in IT sector > ₹2000 Cr',
    reasons: ['✓ Breakout above 50-EMA', '✓ Heavy FII Accumulation', '✓ Volume 2.4x Average', '✓ Sector Rotation Leadership'],
  },

  HDFCBANK: {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Limited',
    cmp: 1610.2,
    trend: 'Bullish Continuation',
    momentumScore: 88,
    institutionalScore: 91,
    newsScore: 85,
    technicalScore: 89,
    fundamentalScore: 96,
    volumeScore: 86,
    riskScore: 88,
    confidenceScore: 90,
    overallOpportunityScore: 90,
    signal: 'BUY / ACCUMULATE',
    entryZone: '₹1590 - ₹1615',
    stopLoss: '₹1550',
    targetZone: '₹1720 - ₹1780',
    holdingPeriod: '15 Days',
    invalidation: 'NIM margin drop > 25 bps or breakdown below ₹1550',
    reasons: ['✓ Private Banking Leadership', '✓ FII Inflows resuming', '✓ Valuation at 14.5x Forward PE'],
  },

  INFY: {
    symbol: 'INFY',
    name: 'Infosys Limited',
    cmp: 1512.4,
    trend: 'Consolidation / Accumulation',
    momentumScore: 82,
    institutionalScore: 86,
    newsScore: 84,
    technicalScore: 84,
    fundamentalScore: 92,
    volumeScore: 80,
    riskScore: 84,
    confidenceScore: 85,
    overallOpportunityScore: 86,
    signal: 'ACCUMULATE ON PULLBACK',
    entryZone: '₹1485 - ₹1505',
    stopLoss: '₹1440',
    targetZone: '₹1620',
    holdingPeriod: '20 Days',
    invalidation: 'Close below ₹1440',
    reasons: ['✓ Cloud & Topaz AI Deal Wins', '✓ Solid ROE 38.6%', '✓ Zero Debt'],
  },

  RELIANCE: {
    symbol: 'RELIANCE',
    name: 'Reliance Industries',
    cmp: 2580.6,
    trend: 'Bearish / Distribution',
    momentumScore: 42,
    institutionalScore: 48,
    newsScore: 60,
    technicalScore: 45,
    fundamentalScore: 88,
    volumeScore: 40,
    riskScore: 55,
    confidenceScore: 88,
    overallOpportunityScore: 45,
    signal: 'AVOID / TRIM',
    entryZone: 'N/A',
    stopLoss: 'N/A',
    targetZone: 'N/A',
    holdingPeriod: 'N/A',
    invalidation: 'N/A',
    reasons: ['⚠️ Institutional Distribution', '⚠️ Weak Volume', '⚠️ O2C refining margin pressure'],
  }
};

export default TRACKED_STOCKS_PROFILES;
