/**
 * CompanyDatabase - Institutional Database of Listed Indian Enterprises
 */
export const COMPANY_DATABASE = {
  INFY: {
    symbol: 'INFY',
    name: 'Infosys Limited',
    sector: 'Information Technology',
    industry: 'IT Services & Consulting',
    marketCap: '₹6,28,450 Cr',
    marketCapCategory: 'Large Cap',
    listingDate: '1993-06-14',
    exchange: 'NSE / BSE / NASDAQ (ADR)',
    cmp: 1512.4,
    businessDescription: 'Infosys is a global leader in next-generation digital services and consulting. It enables clients in 56+ countries to navigate their digital transformation powered by Cloud and AI (Topaz platform).',
    management: {
      ceo: 'Salil Parekh',
      cfo: 'Jayesh Sanghrajka',
      chairman: 'Nandan Nilekani',
      boardIndependence: '82% Independent Directors',
      promoterHolding: 14.7,
      promoterPledge: 0.0,
      fiiHolding: 33.2,
      diiHolding: 36.8,
      publicHolding: 15.3,
    },
    businessMix: [
      { segment: 'Financial Services', pct: 27.5 },
      { segment: 'Retail & CPG', pct: 14.8 },
      { segment: 'High Tech', pct: 7.8 },
      { segment: 'Manufacturing', pct: 14.5 },
      { segment: 'Energy & Utilities', pct: 12.8 },
      { segment: 'Life Sciences', pct: 7.4 },
      { segment: 'Communication', pct: 15.2 },
    ],
    geographicalMix: [
      { region: 'North America', pct: 59.8 },
      { region: 'Europe', pct: 28.6 },
      { region: 'Rest of World', pct: 9.2 },
      { region: 'India', pct: 2.4 },
    ],
    competitors: ['TCS', 'WIPRO', 'HCLTECH', 'TECHM', 'Cognizant', 'Accenture'],
    financials: {
      revenue: [121641, 146767, 153670, 162100], // Last 4 FYs in Cr
      netProfit: [22110, 24095, 26233, 27800],
      operatingMargin: 21.2,
      netMargin: 17.1,
      roe: 38.6,
      roce: 44.2,
      debtToEquity: 0.04,
      currentRatio: 2.1,
      pe: 24.8,
      forwardPe: 21.5,
      pb: 8.2,
      evEbitda: 17.4,
      peg: 1.8,
      fcfCr: 22400,
      dividendYield: 2.4,
      receivableDays: 68,
      cashConversionCycle: 42,
    },
    growth: {
      revenueCagr3Y: 10.8,
      profitCagr3Y: 8.4,
      fcfGrowth3Y: 12.1,
      yoyRevenueGrowth: 4.2,
      yoyProfitGrowth: 6.8,
    },
    moat: {
      score: 88,
      type: 'Wide Moat',
      drivers: ['High Switching Costs (Mission-critical core systems)', 'Global Delivery Network', 'Brand Reputation'],
    },
    redFlags: [],
  },

  TCS: {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    sector: 'Information Technology',
    industry: 'IT Services & Consulting',
    marketCap: '₹15,02,100 Cr',
    marketCapCategory: 'Mega Cap',
    listingDate: '2004-08-25',
    exchange: 'NSE / BSE',
    cmp: 4150.0,
    businessDescription: 'TCS is the IT services, consulting, and business solutions organization that has been partnering with many of the world\'s largest businesses in their transformation journeys for over 50 years.',
    management: {
      ceo: 'K. Krithivasan',
      cfo: 'Samir Seksaria',
      chairman: 'N. Chandrasekaran',
      boardIndependence: '75% Independent Directors',
      promoterHolding: 72.4,
      promoterPledge: 0.0,
      fiiHolding: 12.4,
      diiHolding: 10.8,
      publicHolding: 4.4,
    },
    businessMix: [
      { segment: 'BFSI', pct: 31.8 },
      { segment: 'Consumer Business', pct: 15.2 },
      { segment: 'Life Sciences & Healthcare', pct: 11.0 },
      { segment: 'Manufacturing', pct: 8.8 },
      { segment: 'Technology & Services', pct: 8.5 },
      { segment: 'Regional Markets', pct: 24.7 },
    ],
    geographicalMix: [
      { region: 'North America', pct: 50.2 },
      { region: 'Continental Europe', pct: 15.6 },
      { region: 'UK', pct: 16.8 },
      { region: 'India', pct: 6.2 },
      { region: 'Asia Pacific', pct: 11.2 },
    ],
    competitors: ['INFY', 'WIPRO', 'HCLTECH', 'Accenture', 'Capgemini'],
    financials: {
      revenue: [191754, 225458, 240893, 255200],
      netProfit: [38327, 42147, 45908, 48900],
      operatingMargin: 24.5,
      netMargin: 19.1,
      roe: 45.2,
      roce: 52.8,
      debtToEquity: 0.0,
      currentRatio: 2.6,
      pe: 28.4,
      forwardPe: 25.2,
      pb: 12.1,
      evEbitda: 20.1,
      peg: 2.4,
      fcfCr: 41200,
      dividendYield: 1.8,
      receivableDays: 62,
      cashConversionCycle: 38,
    },
    growth: {
      revenueCagr3Y: 11.2,
      profitCagr3Y: 9.8,
      fcfGrowth3Y: 10.5,
      yoyRevenueGrowth: 5.6,
      yoyProfitGrowth: 7.2,
    },
    moat: {
      score: 94,
      type: 'Wide Moat',
      drivers: ['Scale Advantage (600k+ employees)', 'Deep Client Lock-in (98% repeat business)', 'Zero Net Debt'],
    },
    redFlags: [],
  },

  RELIANCE: {
    symbol: 'RELIANCE',
    name: 'Reliance Industries Limited',
    sector: 'Conglomerate / Energy & Retail',
    industry: 'Oil & Gas, Retail, Telecom (Jio)',
    marketCap: '₹17,45,800 Cr',
    marketCapCategory: 'Mega Cap',
    listingDate: '1977-11-20',
    exchange: 'NSE / BSE',
    cmp: 2580.6,
    businessDescription: 'Reliance Industries is India\'s largest private sector company, with businesses spanning oil-to-chemicals (O2C), retail, digital services (Jio), green energy, and media.',
    management: {
      ceo: 'Mukesh Ambani',
      cfo: 'V. Srikanth',
      chairman: 'Mukesh Ambani',
      boardIndependence: '50% Independent Directors',
      promoterHolding: 50.3,
      promoterPledge: 0.0,
      fiiHolding: 21.8,
      diiHolding: 16.5,
      publicHolding: 11.4,
    },
    businessMix: [
      { segment: 'Oil to Chemicals (O2C)', pct: 54.2 },
      { segment: 'Reliance Retail', pct: 28.5 },
      { segment: 'Jio Digital Services', pct: 14.8 },
      { segment: 'Oil & Gas Exploration', pct: 2.5 },
    ],
    geographicalMix: [
      { region: 'India', pct: 64.5 },
      { region: 'Exports / Global', pct: 35.5 },
    ],
    competitors: ['IOC', 'BPCL', 'Avenue Supermarts (DMart)', 'Bharti Airtel'],
    financials: {
      revenue: [700000, 879468, 896943, 980000],
      netProfit: [60705, 66702, 69624, 74200],
      operatingMargin: 16.4,
      netMargin: 7.6,
      roe: 10.8,
      roce: 9.8,
      debtToEquity: 0.42,
      currentRatio: 1.1,
      pe: 22.1,
      forwardPe: 19.5,
      pb: 2.4,
      evEbitda: 12.8,
      peg: 1.9,
      fcfCr: 18500,
      dividendYield: 0.4,
      receivableDays: 22,
      cashConversionCycle: 14,
    },
    growth: {
      revenueCagr3Y: 12.4,
      profitCagr3Y: 7.2,
      fcfGrowth3Y: -4.5,
      yoyRevenueGrowth: 9.2,
      yoyProfitGrowth: 6.6,
    },
    moat: {
      score: 85,
      type: 'Wide Moat',
      drivers: ['Jio Telecom Monopoly/Duopoly (470M+ subscribers)', 'Retail scale advantage (18,000+ stores)', 'Refining complexity index'],
    },
    redFlags: ['High Capex burden for New Energy gigafactories'],
  },

  HDFCBANK: {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Limited',
    sector: 'Banking & Financial Services',
    industry: 'Private Sector Banking',
    marketCap: '₹12,24,000 Cr',
    marketCapCategory: 'Mega Cap',
    listingDate: '1995-11-08',
    exchange: 'NSE / BSE / NYSE (ADR)',
    cmp: 1610.2,
    businessDescription: 'HDFC Bank is India\'s largest private sector bank by assets. Following its landmark merger with parent HDFC Ltd, it offers full-suite retail, wholesale, and housing finance services.',
    management: {
      ceo: 'Sashidhar Jagdishan',
      cfo: 'Srinivasan Vaidyanathan',
      chairman: 'Atanu Chakraborty',
      boardIndependence: '80% Independent Directors',
      promoterHolding: 0.0, // Merged institutional entity
      promoterPledge: 0.0,
      fiiHolding: 47.8,
      diiHolding: 31.2,
      publicHolding: 21.0,
    },
    businessMix: [
      { segment: 'Retail Banking', pct: 45.2 },
      { segment: 'Wholesale Banking', pct: 38.4 },
      { segment: 'Mortgages & Housing', pct: 12.8 },
      { segment: 'Treasury & Other', pct: 3.6 },
    ],
    geographicalMix: [
      { region: 'India (9,000+ branches)', pct: 100.0 },
    ],
    competitors: ['ICICIBANK', 'AXISBANK', 'KOTAKBANK', 'SBIN'],
    financials: {
      revenue: [157250, 192000, 315000, 385000],
      netProfit: [36961, 44108, 60810, 68500],
      operatingMargin: 42.1,
      netMargin: 17.8,
      roe: 16.5,
      roce: 15.2,
      debtToEquity: 6.8, // Banking leverage standard
      currentRatio: 1.0,
      pe: 16.8,
      forwardPe: 14.5,
      pb: 2.1,
      evEbitda: 11.2,
      peg: 1.1,
      fcfCr: 45000,
      dividendYield: 1.2,
      receivableDays: 0,
      cashConversionCycle: 0,
    },
    growth: {
      revenueCagr3Y: 22.4,
      profitCagr3Y: 18.2,
      fcfGrowth3Y: 15.4,
      yoyRevenueGrowth: 14.5,
      yoyProfitGrowth: 16.2,
    },
    moat: {
      score: 91,
      type: 'Wide Moat',
      drivers: ['CASA Ratio Advantage (~38%)', 'Lowest Cost of Funds in Private Banking', 'Distribution Network (9,000+ branches)'],
    },
    redFlags: ['Post-merger NIM compression temporarily monitoring phase'],
  }
};

export const getCompanyProfile = (ticker) => {
  const upper = ticker ? ticker.toUpperCase() : 'INFY';
  return COMPANY_DATABASE[upper] || COMPANY_DATABASE.INFY;
};

export default COMPANY_DATABASE;
